### ISSUE TITLE
V.1.0.1 Fehler im Labelmodus (Creating) bei gleichzeitigem Klick von linker + rechter Maustaste

### ISSUE THREAD

**Issue by Retzi** [MaKaNu/ROISA-Region_of_Interest_Selector_Automat#6]
Wenn man im Creatingmodus labeln möchte und die linke und rechte Maustaste gleichzeitig drückt, wird das Fenstern automatisch gestartet und erst bei einem erneuten Linksklick an der gewünschten Stelle beendet. Jedoch wird beim Beenden des einen Fenster ein neues gleichzeitig gestartet. Es durch den Wechsel zu einem anderen Bild (mit den Tasten A oder D) führt zu einem "Abbruch" der Problems.
Auch das Entfernen von Labels mit Hilfe der Taste "Entf" in "Box Labels" führt nicht zu einem Abbruch des Problems. Sobald der Mauszeiger in dem Bereich des Bildes gelangt kommt es zu dem oben beschriebenen Problem.

**Comment by MaKaNu** [comment]
The problem was caused inside the mousePressEvent of the Canvas class. The if condition was always true because the statement works inside the mouseMoveEvent but not inside the press and release Events.

The Fix is pushed on Dev branch and will be included next master merge.
